version: "3.9"

services:
  flask-app:
    image: python:3.10
    command: bash -c "cd app/ && pip install -r requirements.txt && python app.py"
    volumes:
      - ./backend_v2:/app
    ports:
      - "5000:5000"
    restart: always
  frontend:
    container_name: textgrader_frontend
    image: node:lts-alpine
    working_dir: "/frontend"
    command: sh -c "yarn && yarn prod"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    restart: always
    #nginx:
    #image: nginx:latest
    #ports:
    #  - "8080:80"
    #volumes:
    #  - ./nginx.conf:/etc/nginx/nginx.conf
    #depends_on:
    #  - flask-app
    #  - frontend

