version: "3.9"

services:
  backend:
    container_name: backend
    image: python:3.10
    working_dir: "/backend"
    #command: sh -c "
    #  python -m venv venv && . venv/bin/activate && pip install -U pip &&
    #  cd src && pip3 install -r requirements.txt && python enem_essays.py && python run.py task general_tasks task_correct_essays &&
    #  python run.py task general_tasks task_pipeline_essays && uvicorn api:app --host 0.0.0.0 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    networks:
      - some_net

  frontend:
    image: python:3.8
    container_name: frontend
    command: bash -c "pip install django && ls -a && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./frontend:/frontend/textgrader
    ports:
      - "3000:8000"
    working_dir: /frontend/textgrader

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=text-grader
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      # copy the sql script to create tables
      #- ./sql/start-db.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - some_net

networks:
  some_net: