version: "3.9"

services:
  backend:
    container_name: textgrader_backend
    image: python:3.10
    working_dir: "/backend"
    command: sh -c "
      python -m venv venv && . venv/bin/activate && pip install -U pip &&
      pip install -U "jax[cpu]" tensorflow-cpu tensorflow_text tensorflow_hub scikit-learn nltk gensim pyarrow psycopg2-binary &&
      pip install -U pandas fastapi "uvicorn[standard]" orjson openpyxl colorlog pyspellchecker coloredlogs &&
      cd src && python requirements.py && python run.py task general_tasks task_correct_essays &&
      python run.py task general_tasks task_pipeline_essays && uvicorn api:app --host 0.0.0.0 --reload"
    ports:
      - 3006:8000
    volumes:
      - ./backend:/backend
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
    restart: always
    networks:
      - app_network

  frontend:
    container_name: textgrader_frontend
    image: node:lts-alpine
    working_dir: "/frontend"
    command: sh -c "yarn && yarn prod"
    ports:
      - 3005:3000
    volumes:
      - ./frontend:/frontend
    restart: always
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
    restart: always
    networks:
      - app_network

volumes:
  postgres-data:

networks:
  app_network:
    external: true
    name: app_network


