version: "3.9"

services:
  flask-app:
    image: python:3.10
    command: bash -c "cd app/ && pip install -r requirements.txt && python app.py"
    volumes:
      - ./backend_v2:/app
    ports:
      - "5000:5000"
  frontend:
    container_name: frontend
    image: node:lts-alpine
    working_dir: "/frontend"
    command: sh -c "yarn && yarn dev"
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
