# Generated by Django 4.2.3 on 2023-07-30 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("context", models.TextField(verbose_name="Contexto")),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Essay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("content", models.TextField(default="", verbose_name="Conteúdo")),
                ("grade", models.FloatField(default=0.0, verbose_name="Nota")),
                (
                    "origin",
                    models.CharField(
                        choices=[("UOL", "UOL"), ("BRASIL_ESCOLA", "Brasil Escola")],
                        default="UOL",
                        max_length=20,
                    ),
                ),
                ("analysis", models.TextField(default="", verbose_name="Correção")),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="essays.theme",
                        verbose_name="Tema",
                    ),
                ),
            ],
        ),
    ]
