# Generated by Django 4.2.3 on 2023-07-31 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("essays", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="essay",
            old_name="analysis",
            new_name="comments",
        ),
    ]
