# Generated by Django 4.2.3 on 2023-07-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essays", "0002_rename_analysis_essay_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="essay",
            name="corrected",
            field=models.BooleanField(default=False, verbose_name="Corrigido"),
        ),
    ]
